openapi: 3.0.1
security:
  - basicAuth: []
info:
  title: Whiskey API
  description: |
    ## Whiskey API

    This is the whiskey API provided by Hungovercoders.

    ![Hungovercoders](https://www.hungovercoders.com/assets/logo3.ico)

    These are the services levels available:

    | Name | Description |
    | --- | --- |
    | Basic | Free tier available to all consumers |

  version: "0.0"
tags:
  - name: whiskey
    description: Whiskey operations
paths:
  /whiskey/{id}:
    get:
      summary: Get a specific whiskey
      operationId: getAWhiskey
      tags: 
        - whiskey
      parameters:
        - name: id
          in: path
          description: The ID of the whiskey to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Whiskey'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid ID supplied
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Whiskey not found

components:
  schemas:
    Whiskey:
      title: Whiskey
      description: A whiskey object
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 50
        age:
          type: integer
          minimum: 3
          maximum: 200
        abv:
          type: number
          minimum: 0
          maximum: 92
        distillery:
          type: string
          minLength: 1
          maxLength: 50
        type: 
          type: string
          enum:
            - Single Malt
            - Blended
            - Bourbon
            - Rye
            - Corn
            - Wheat
            - Other
        country:
          type: string
          enum:
            - Scotland
            - Ireland
            - USA
            - Canada
            - Japan
            - Wales
            - England
            - India
            - Australia
            - Other
      additionalProperties: false
  securitySchemes:
    apiKey:
      description: API Key
      type: apiKey
      name: api-key
      in: header
    basicAuth:
      description: Basic Authentication
      type: http
      scheme: basic