# version: '3'

# services:
#   docusaurus:
#     build:
#       context: .
#     ports:
#       - 3000:3000
#     volumes:
#       - ./docs:/app/docs
#       - ./src:/app/src
#       - ./static:/app/static
#       - ./docusaurus.config.js:/app/docusaurus.config.js
#       - ./sidebars.js:/app/sidebars.js


version: '3.8'

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
